version: "3.9"

services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.rule=Host(`nexus-devops.com`)"
      - "traefik.http.routers.nexus.entrypoints=web"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081" # Adjust port as needed
    ports:
      - "8081:8081"
    networks:
      - devops-network

  traefik:
    image: traefik:2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik-devops.com`)"
      - "traefik.http.routers.traefik.entrypoints=web"

volumes:
  nexus-data: {}

networks:
  devops-network:
    driver: bridge
